import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Download, TrendingUp, Calendar } from "lucide-react";
import { RevenueBarChart } from "@/components/analytics/revenue-bar-chart";

export default function RevenueAnalyticsPage() {
  return (
    <div className="max-w-6xl mx-auto">
      {/* Header Section */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Revenue Analytics</h1>
          <p className="text-gray-500 text-sm">Detailed breakdown of revenue generated by Jane Doe.</p>
        </div>
        <Button variant="outline" className="gap-2 font-semibold">
          <Download size={16} /> Export Data
        </Button>
      </div>

      {/* Main Chart Card */}
      <Card className="mb-6 border shadow-sm">
        <CardContent className="p-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between mb-6 gap-4">
            <div>
              <p className="text-sm font-semibold text-gray-500 mb-1">Total Lifetime Value</p>
              <h2 className="text-3xl font-bold text-gray-900 mb-1">$348.00</h2>
              <p className="text-sm text-green-600 font-medium flex items-center gap-1">
                <TrendingUp size={16} /> +12% from last year
              </p>
            </div>

            <div className="flex items-center gap-3">
              {/* Time Toggle */}
              <div className="flex items-center bg-blue-50/50 p-1 rounded-md border border-blue-100">
                <button className="px-4 py-1.5 text-sm font-medium text-gray-500 hover:text-gray-900 rounded-sm">Daily</button>
                <button className="px-4 py-1.5 text-sm font-medium text-gray-500 hover:text-gray-900 rounded-sm">Weekly</button>
                <button className="px-4 py-1.5 text-sm font-medium text-gray-500 hover:text-gray-900 rounded-sm">Monthly</button>
                <button className="px-4 py-1.5 text-sm font-medium text-blue-600 bg-white shadow-sm rounded-sm">Yearly</button>
              </div>

              {/* Date Picker Mock */}
              <Button variant="outline" className="text-gray-600 font-medium gap-2">
                <Calendar size={16} /> Jan 01 - Dec 31, 2026
              </Button>
            </div>
          </div>

          <RevenueBarChart />
        </CardContent>
      </Card>

      {/* Bottom Stats Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="border shadow-sm">
          <CardContent className="p-6">
            <p className="text-sm font-medium text-gray-500 mb-2">Average Revenue Per User</p>
            <h3 className="text-2xl font-bold text-gray-900">$29.00</h3>
          </CardContent>
        </Card>
        <Card className="border shadow-sm">
          <CardContent className="p-6">
            <p className="text-sm font-medium text-gray-500 mb-2">Active Subscriptions</p>
            <h3 className="text-2xl font-bold text-gray-900">1</h3>
          </CardContent>
        </Card>
        <Card className="border shadow-sm">
          <CardContent className="p-6">
            <p className="text-sm font-medium text-gray-500 mb-2">Total Transactions</p>
            <h3 className="text-2xl font-bold text-gray-900">12</h3>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}